Add Apple 2020 iPhone and iPad device info
lmirosevic/GBDeviceInfo pull request #115
Opened 2020-10-24 08:17 UTC by LisonFan

add iPhone 12 mini, iPhone 12, iPhone 12 Pro, iPhone 12 Pro Max and iPad Air4 models info.
Adjust the sorting of iPad models info by screen size and release year.

https://www.theiphonewiki.com/wiki/Models

https://www.apple.com/iphone-12-pro/specs/
https://www.apple.com/iphone-12/specs/

https://www.apple.com/ipad-air/specs/
![image](https://user-images.githubusercontent.com/9424775/97076422-39cfaa80-1614-11eb-9128-2816dede4734.png)

2020-10-26 12:52 UTC, goncharik requested changes

2020-10-26 12:52 UTC, goncharik commented on GBDeviceInfo/GBDeviceInfo_iOS.m
> +                @[@12, @8]: @[@(GBDeviceModeliPhoneSE2), @"iPhone SE 2", @(GBDeviceDisplay4p7Inch), @326],
Let's keep sorting by device version numbers

2020-10-26 12:52 UTC, goncharik commented on GBDeviceInfo/GBDeviceInfo_iOS.m
> +                @[@6, @11]: @[@(GBDeviceModeliPad5), @"iPad 2017", @(GBDeviceDisplay9p7Inch), @264],
Let's keep sorting by device version numbers

2020-10-26 13:18 UTC, goncharik commented
Please add iPad 8th Gen as well - https://www.theiphonewiki.com/wiki/IPad_(8th_generation)

2020-11-06 08:34 UTC, lmirosevic commented
Merged #116 instead. 

Thanks to both @goncharik and @LisonFan

2020-11-06 08:34 UTC, closed without merging